fix systemd-boot

diff --git a/abif b/abif
--- a/abif
+++ b/abif
@@ -197,7 +197,6 @@ id_system() {
       SYSTEM="BIOS"
     fi
          
-
 }   
  
 
@@ -344,9 +343,9 @@ set_hw_clock() {
 generate_fstab() {
 
     dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_ConfBseFstab " --menu "$_FstabBody" 0 0 4 \
+	"genfstab -U -p" "$_FstabDevUUID" \
 	"genfstab -p" "$_FstabDevName" \
 	"genfstab -L -p" "$_FstabDevLabel" \
-	"genfstab -U -p" "$_FstabDevUUID" \
 	"genfstab -t PARTUUID -p" "$_FstabDevPtUUID" 2>${ANSWER}
 	
 	if [[ $(cat ${ANSWER}) != "" ]]; then
@@ -384,7 +383,7 @@ set_hostname() {
    dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_ConfBseHost " --inputbox "$_HostNameBody" 0 0 "pacbang" 2>${ANSWER} || config_base_menu
 
    echo "$(cat ${ANSWER})" > ${MOUNTPOINT}/etc/hostname 2>/tmp/.errlog
-   echo -e "#<ip-address>\t<hostname.domain.org>\t<hostname>\n127.0.0.1\tlocalhost.localdomain\tlocalhost\t$(cat ${ANSWER})\n::1\tlocalhost.localdomain\tlocalhost\t$(cat ${ANSWER})" > ${MOUNTPOINT}/etc/hosts 2>>/tmp/.errlog
+   echo -e "#ip-address\thostname.domain.org\thostname\n127.0.0.1\tlocalhost.localdomain\tlocalhost\n::1\tlocalhost\n127.0.1.1\t$(cat ${ANSWER}).localdomain\t$(cat ${ANSWER})" > ${MOUNTPOINT}/etc/hosts 2>>/tmp/.errlog
    check_for_error
 }
 
@@ -593,67 +592,70 @@ find_partitions() {
 # Create partitions.
 create_partitions(){
 
-# Securely destroy all data on a given device.
-secure_wipe(){
-	
-	# Warn the user. If they proceed, wipe the selected device.
-	dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PartOptWipe " --yesno "$_AutoPartWipeBody1 ${DEVICE} $_AutoPartWipeBody2" 0 0
-	if [[ $? -eq 0 ]]; then
+	# Securely destroy all data on a given device.
+	secure_wipe(){
 		
-		clear
-		wipe -Ifre ${DEVICE}
-		
-		# Alternate dd command - requires pv to be installed
-		#dd if=/dev/zero | pv | dd of=${DEVICE} iflag=nocache oflag=direct bs=4096 2>/tmp/.errlog
-    else
-		create_partitions
-    fi
-}
-
-
-# BIOS and UEFI
-auto_partition(){
-	
-	# Provide warning to user
-	dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepPartDisk " --yesno "$_AutoPartBody1 $DEVICE $_AutoPartBody2 $_AutoPartBody3" 0 0
-	
-	if [[ $? -eq 0 ]]; then
-		
-		# Find existing partitions (if any) to remove
-		parted -s ${DEVICE} print | awk '/^ / {print $1}' > /tmp/.del_parts
-	
-		for del_part in $(tac /tmp/.del_parts); do
-			parted -s ${DEVICE} rm ${del_part} 2>/tmp/.errlog
-			check_for_error
-		done
- 
-		# Identify the partition table
-		part_table=$(parted -s ${DEVICE} print | grep -i 'partition table' | awk '{print $3}')
- 
-		# Create partition table if one does not already exist
-		([[ $SYSTEM == "BIOS" ]] && [[ $part_table != "msdos" ]]) && parted -s ${DEVICE} mklabel msdos 2>/tmp/.errlog
-		([[ $SYSTEM == "UEFI" ]] && [[ $part_table != "gpt" ]]) && parted -s ${DEVICE} mklabel gpt 2>/tmp/.errlog
-		check_for_error
-		
-		# Create paritions (same basic partitioning scheme for BIOS and UEFI)
-		if [[ $SYSTEM == "BIOS" ]]; then
-			parted -s ${DEVICE} mkpart primary ext3 1MiB 513MiB 2>/tmp/.errlog
+		# Warn the user. If they proceed, wipe the selected device.
+		dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PartOptWipe " --yesno "$_AutoPartWipeBody1 ${DEVICE} $_AutoPartWipeBody2" 0 0
+		if [[ $? -eq 0 ]]; then
+			
+			clear
+			wipe -Ifre ${DEVICE}
+			
+			# Alternate dd command - requires pv to be installed
+			#dd if=/dev/zero | pv | dd of=${DEVICE} iflag=nocache oflag=direct bs=4096 2>/tmp/.errlog
 		else
-			parted -s ${DEVICE} mkpart ESP fat32 1MiB 513MiB 2>/tmp/.errlog
+			create_partitions
 		fi
+	}
+
+
+	# BIOS and UEFI
+	auto_partition(){
 		
-		parted -s ${DEVICE} set 1 boot on 2>>/tmp/.errlog
-		parted -s ${DEVICE} mkpart primary ext3 513MiB 100% 2>>/tmp/.errlog
-		check_for_error
+		# Provide warning to user
+		dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepPartDisk " --yesno "$_AutoPartBody1 $DEVICE $_AutoPartBody2 $_AutoPartBody3" 0 0
+		
+		if [[ $? -eq 0 ]]; then
+			
+			# Find existing partitions (if any) to remove
+			parted -s ${DEVICE} print | awk '/^ / {print $1}' > /tmp/.del_parts
+		
+			for del_part in $(tac /tmp/.del_parts); do
+				parted -s ${DEVICE} rm ${del_part} 2>/tmp/.errlog
+				check_for_error
+			done
+	 
+			# Identify the partition table
+			part_table=$(parted -s ${DEVICE} print | grep -i 'partition table' | awk '{print $3}')
+	 
+			# Create partition table if one does not already exist
+			([[ $SYSTEM == "BIOS" ]] && [[ $part_table != "msdos" ]]) && parted -s ${DEVICE} mklabel msdos 2>/tmp/.errlog
+			([[ $SYSTEM == "UEFI" ]] && [[ $part_table != "gpt" ]]) && parted -s ${DEVICE} mklabel gpt 2>/tmp/.errlog
+			check_for_error
+			
+			# Create partitions (same basic partitioning scheme for BIOS and UEFI)
+			if [[ $SYSTEM == "BIOS" ]]; then
+				parted -s ${DEVICE} mkpart primary ext3 1MiB 513MiB 2>/tmp/.errlog
+				parted -s ${DEVICE} set 1 boot on 2>>/tmp/.errlog
+			else
+				parted -s ${DEVICE} mkpart primary fat32 1MiB 513MiB 2>/tmp/.errlog
+				parted -s ${DEVICE} set 1 esp on 2>>/tmp/.errlog
+			fi
+			
+			# Create root partition
+			parted -s ${DEVICE} mkpart primary ext3 513MiB 100% 2>>/tmp/.errlog
+			
+			check_for_error
 
-        # Show created partitions
-        lsblk ${DEVICE} -o NAME,TYPE,FSTYPE,SIZE > /tmp/.devlist
-        dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "" --textbox /tmp/.devlist 0 0
-    else
-        create_partitions
-    fi
+			# Show created partitions
+			lsblk ${DEVICE} -o NAME,TYPE,FSTYPE,SIZE > /tmp/.devlist
+			dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "" --textbox /tmp/.devlist 0 0
+		else
+			create_partitions
+		fi
 
-}
+	}
 
     dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "$_PartToolTitle" --menu "$_PartToolBody" 0 0 5 \
     "$_PartOptWipe" "BIOS & UEFI" \
@@ -691,7 +693,7 @@ select_filesystem(){
 	"ext2" "mkfs.ext2 -q" \
 	"ext3" "mkfs.ext3 -q" \
 	"ext4" "mkfs.ext4 -q" \
-	"f2fs" "mkfs.f2fs" \
+	"f2fs" "mkfs.f2fs -f" \
 	"jfs" "mkfs.jfs -q" \
 	"nilfs2" "mkfs.nilfs2 -q" \
 	"ntfs" "mkfs.ntfs -q" \
@@ -712,7 +714,7 @@ select_filesystem(){
 					CHK_NUM=8
 					fs_opts="data=journal data=writeback dealloc discard noacl noatime nobarrier nodelalloc"
 					;;
-		"f2fs") 	FILESYSTEM="mkfs.f2fs"
+		"f2fs") 	FILESYSTEM="mkfs.f2fs -f"
 					fs_opts="data_flush disable_roll_forward disable_ext_identify discard fastboot flush_merge inline_xattr inline_data inline_dentry no_heap noacl nobarrier noextent_cache noinline_data norecovery"
 					CHK_NUM=16
 					modprobe f2fs
@@ -754,154 +756,155 @@ select_filesystem(){
   
 mount_partitions() {
 
-# This subfunction allows for special mounting options to be applied for relevant fs's.
-# Seperate subfunction for neatness.
-mount_opts() {
+	# This subfunction allows for special mounting options to be applied for relevant fs's.
+	# Seperate subfunction for neatness.
+	mount_opts() {
 
-	FS_OPTS=""
-	echo "" > ${MOUNT_OPTS}
-	
-	for i in ${fs_opts}; do
-		FS_OPTS="${FS_OPTS} ${i} - off"
-	done
-
-	dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $(echo $FILESYSTEM | sed "s/.*\.//g" | sed "s/-.*//g") " --checklist "$_btrfsMntBody" 0 0 $CHK_NUM \
-	$FS_OPTS 2>${MOUNT_OPTS}
-	
-	# Now clean up the file
-	sed -i 's/ /,/g' ${MOUNT_OPTS}
-	sed -i '$s/,$//' ${MOUNT_OPTS}
-
-	# If mount options selected, confirm choice 
-	if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then
-		dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_MntStatusTitle " --yesno "\n${_btrfsMntConfBody}$(cat ${MOUNT_OPTS})\n" 10 75
-		[[ $? -eq 1 ]] && mount_opts
-	fi 
-   
-}
-
-# Subfunction to save repetition of code
-mount_current_partition(){
-	
-	# Make the mount directory
-	mkdir -p ${MOUNTPOINT}${MOUNT} 2>/tmp/.errlog
-	
-	# Get mounting options for appropriate filesystems
-    [[ $fs_opts != "" ]] && mount_opts
+		FS_OPTS=""
+		echo "" > ${MOUNT_OPTS}
 		
-	# Use special mounting options if selected, else standard mount
-	if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then
-		mount -o $(cat ${MOUNT_OPTS}) ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog
-	else
-		mount ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog
-	fi
-	
-	check_for_error
-	confirm_mount ${MOUNTPOINT}${MOUNT}
-
-	# Identify if mounted partition is type "crypt" (LUKS on LVM, or LUKS alone)
-	if [[ $(lsblk -lno TYPE ${PARTITION} | grep "crypt") != "" ]]; then
-
-        # cryptname for bootloader configuration either way
-		LUKS=1
-		LUKS_NAME=$(echo ${PARTITION} | sed "s~^/dev/mapper/~~g")
-
-		# Check if LUKS on LVM (parent = lvm /dev/mapper/...) 
-		cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "lvm" | grep -i "crypto_luks" | uniq | awk '{print "/dev/mapper/"$1}')
-		for i in ${cryptparts}; do
-			if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
-				LUKS_DEV="$LUKS_DEV cryptdevice=${i}:$LUKS_NAME"
-				LVM=1
-				break;
-			fi
+		for i in ${fs_opts}; do
+			FS_OPTS="${FS_OPTS} ${i} - off"
 		done
+
+		dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $(echo $FILESYSTEM | sed "s/.*\.//g" | sed "s/-.*//g") " --checklist "$_btrfsMntBody" 0 0 $CHK_NUM \
+		$FS_OPTS 2>${MOUNT_OPTS}
 		
-		# Check if LUKS alone (parent = part /dev/...)
-		cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "part" | grep -i "crypto_luks" | uniq | awk '{print "/dev/"$1}')
-		for i in ${cryptparts}; do
-			if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
-				LUKS_UUID=$(lsblk -lno UUID,TYPE,FSTYPE ${i} | grep "part" | grep -i "crypto_luks" | awk '{print $1}')
-				LUKS_DEV="$LUKS_DEV cryptdevice=UUID=$LUKS_UUID:$LUKS_NAME"
-				break;
-			fi
-		done
-	
-	# If LVM logical volume....
-	elif [[ $(lsblk -lno TYPE ${PARTITION} | grep "lvm") != "" ]]; then
-		LVM=1
+		# Now clean up the file
+		sed -i 's/ /,/g' ${MOUNT_OPTS}
+		sed -i '$s/,$//' ${MOUNT_OPTS}
+
+		# If mount options selected, confirm choice 
+		if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then
+			dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_MntStatusTitle " --yesno "\n${_btrfsMntConfBody}$(cat ${MOUNT_OPTS})\n" 10 75
+			[[ $? -eq 1 ]] && mount_opts
+		fi 
+	   
+	}
+
+	# Subfunction to save repetition of code
+	mount_current_partition(){
 		
-		# First get crypt name (code above would get lv name)
-		cryptparts=$(lsblk -lno NAME,TYPE,FSTYPE | grep "crypt" | grep -i "lvm2_member" | uniq | awk '{print "/dev/mapper/"$1}')
-		for i in ${cryptparts}; do
-			if [[ $(lsblk -lno NAME ${i} | grep $(echo $PARTITION | sed "s~^/dev/mapper/~~g")) != "" ]]; then
-				LUKS_NAME=$(echo ${i} | sed s~/dev/mapper/~~g)
-				break;
-			fi
-		done
+		# Make the mount directory
+		mkdir -p ${MOUNTPOINT}${MOUNT} 2>/tmp/.errlog
 		
-		# Now get the device (/dev/...) for the crypt name
-		cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "part" | grep -i "crypto_luks" | uniq | awk '{print "/dev/"$1}')
-		for i in ${cryptparts}; do
-			if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
-				# Create UUID for comparison
-				LUKS_UUID=$(lsblk -lno UUID,TYPE,FSTYPE ${i} | grep "part" | grep -i "crypto_luks" | awk '{print $1}')
-				
-				# Check if not already added as a LUKS DEVICE (i.e. multiple LVs on one crypt). If not, add.
-				if [[ $(echo $LUKS_DEV | grep $LUKS_UUID) == "" ]]; then
-					LUKS_DEV="$LUKS_DEV cryptdevice=UUID=$LUKS_UUID:$LUKS_NAME"
-					LUKS=1
+		# Get mounting options for appropriate filesystems
+		[[ $fs_opts != "" ]] && mount_opts
+			
+		# Use special mounting options if selected, else standard mount
+		if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then
+			mount -o $(cat ${MOUNT_OPTS}) ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog
+		else
+			mount ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog
+		fi
+		
+		check_for_error
+		confirm_mount ${MOUNTPOINT}${MOUNT}
+
+		# Identify if mounted partition is type "crypt" (LUKS on LVM, or LUKS alone)
+		if [[ $(lsblk -lno TYPE ${PARTITION} | grep "crypt") != "" ]]; then
+
+			# cryptname for bootloader configuration either way
+			LUKS=1
+			LUKS_NAME=$(echo ${PARTITION} | sed "s~^/dev/mapper/~~g")
+
+			# Check if LUKS on LVM (parent = lvm /dev/mapper/...) 
+			cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "lvm" | grep -i "crypto_luks" | uniq | awk '{print "/dev/mapper/"$1}')
+			for i in ${cryptparts}; do
+				if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
+					LUKS_DEV="$LUKS_DEV cryptdevice=${i}:$LUKS_NAME"
+					LVM=1
+					break;
 				fi
-				
-				break;
-			fi
-		done
-	fi
+			done
+			
+			# Check if LUKS alone (parent = part /dev/...)
+			cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "part" | grep -i "crypto_luks" | uniq | awk '{print "/dev/"$1}')
+			for i in ${cryptparts}; do
+				if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
+					LUKS_UUID=$(lsblk -lno UUID,TYPE,FSTYPE ${i} | grep "part" | grep -i "crypto_luks" | awk '{print $1}')
+					LUKS_DEV="$LUKS_DEV cryptdevice=UUID=$LUKS_UUID:$LUKS_NAME"
+					break;
+				fi
+			done
+		
+		# If LVM logical volume....
+		elif [[ $(lsblk -lno TYPE ${PARTITION} | grep "lvm") != "" ]]; then
+			LVM=1
+			
+			# First get crypt name (code above would get lv name)
+			cryptparts=$(lsblk -lno NAME,TYPE,FSTYPE | grep "crypt" | grep -i "lvm2_member" | uniq | awk '{print "/dev/mapper/"$1}')
+			for i in ${cryptparts}; do
+				if [[ $(lsblk -lno NAME ${i} | grep $(echo $PARTITION | sed "s~^/dev/mapper/~~g")) != "" ]]; then
+					LUKS_NAME=$(echo ${i} | sed s~/dev/mapper/~~g)
+					break;
+				fi
+			done
+			
+			# Now get the device (/dev/...) for the crypt name
+			cryptparts=$(lsblk -lno NAME,FSTYPE,TYPE | grep "part" | grep -i "crypto_luks" | uniq | awk '{print "/dev/"$1}')
+			for i in ${cryptparts}; do
+				if [[ $(lsblk -lno NAME ${i} | grep $LUKS_NAME) != "" ]]; then
+					# Create UUID for comparison
+					LUKS_UUID=$(lsblk -lno UUID,TYPE,FSTYPE ${i} | grep "part" | grep -i "crypto_luks" | awk '{print $1}')
+					
+					# Check if not already added as a LUKS DEVICE (i.e. multiple LVs on one crypt). If not, add.
+					if [[ $(echo $LUKS_DEV | grep $LUKS_UUID) == "" ]]; then
+						LUKS_DEV="$LUKS_DEV cryptdevice=UUID=$LUKS_UUID:$LUKS_NAME"
+						LUKS=1
+					fi
+					
+					break;
+				fi
+			done
+		fi
 
-	
-}
+		
+	}
 
-# Seperate function due to ability to cancel
-make_swap(){
+	# Seperate function due to ability to cancel
+	make_swap(){
 
-	# Ask user to select partition or create swapfile
-	dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepMntPart " --menu "$_SelSwpBody" 0 0 7 "$_SelSwpNone" $"-" "$_SelSwpFile" $"-" ${PARTITIONS} 2>${ANSWER} || prep_menu  
-    
-	if [[ $(cat ${ANSWER}) != "$_SelSwpNone" ]]; then    
-		PARTITION=$(cat ${ANSWER})
-    
-		if [[ $PARTITION == "$_SelSwpFile" ]]; then
-			total_memory=$(grep MemTotal /proc/meminfo | awk '{print $2/1024}' | sed 's/\..*//')
-			dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_SelSwpFile " --inputbox "\nM = MB, G = GB\n" 9 30 "${total_memory}M" 2>${ANSWER} || make_swap
-			m_or_g=$(cat ${ANSWER})
-	
-			while [[ $(echo ${m_or_g: -1} | grep "M\|G") == "" ]]; do
-				dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_SelSwpFile " --msgbox "\n$_SelSwpFile $_ErrTitle: M = MB, G = GB\n\n" 0 0
+		# Ask user to select partition or create swapfile
+		dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepMntPart " --menu "$_SelSwpBody" 0 0 7 "$_SelSwpNone" $"-" "$_SelSwpFile" $"-" ${PARTITIONS} 2>${ANSWER} || prep_menu  
+		
+		if [[ $(cat ${ANSWER}) != "$_SelSwpNone" ]]; then    
+			PARTITION=$(cat ${ANSWER})
+		
+			if [[ $PARTITION == "$_SelSwpFile" ]]; then
+				total_memory=$(grep MemTotal /proc/meminfo | awk '{print $2/1024}' | sed 's/\..*//')
 				dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_SelSwpFile " --inputbox "\nM = MB, G = GB\n" 9 30 "${total_memory}M" 2>${ANSWER} || make_swap
 				m_or_g=$(cat ${ANSWER})
-			done
+		
+				while [[ $(echo ${m_or_g: -1} | grep "M\|G") == "" ]]; do
+					dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_SelSwpFile " --msgbox "\n$_SelSwpFile $_ErrTitle: M = MB, G = GB\n\n" 0 0
+					dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_SelSwpFile " --inputbox "\nM = MB, G = GB\n" 9 30 "${total_memory}M" 2>${ANSWER} || make_swap
+					m_or_g=$(cat ${ANSWER})
+				done
 
-			fallocate -l ${m_or_g} ${MOUNTPOINT}/swapfile 2>/tmp/.errlog
-			chmod 600 ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
-			mkswap ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
-			swapon ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
-			check_for_error
-			
-		else # Swap Partition
-			# Warn user if creating a new swap
-			if [[ $(lsblk -o FSTYPE  ${PARTITION} | grep -i "swap") != "swap" ]]; then
-				dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepMntPart " --yesno "\nmkswap ${PARTITION}\n\n" 0 0
-				[[ $? -eq 0 ]] && mkswap ${PARTITION} >/dev/null 2>/tmp/.errlog || mount_partitions
+				fallocate -l ${m_or_g} ${MOUNTPOINT}/swapfile 2>/tmp/.errlog
+				chmod 600 ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
+				mkswap ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
+				swapon ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
+				check_for_error
+				
+			else # Swap Partition
+				# Warn user if creating a new swap
+				if [[ $(lsblk -o FSTYPE  ${PARTITION} | grep -i "swap") != "swap" ]]; then
+					dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_PrepMntPart " --yesno "\nmkswap ${PARTITION}\n\n" 0 0
+					[[ $? -eq 0 ]] && mkswap ${PARTITION} >/dev/null 2>/tmp/.errlog || mount_partitions
+				fi
+				# Whether existing to newly created, activate swap
+				swapon  ${PARTITION} >/dev/null 2>>/tmp/.errlog
+				check_for_error
+				# Since a partition was used, remove that partition from the list
+				PARTITIONS=$(echo $PARTITIONS | sed "s~${PARTITION} [0-9]*[G-M]~~" | sed "s~${PARTITION} [0-9]*\.[0-9]*[G-M]~~" | sed s~${PARTITION}$' -'~~)
+				NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS - 1 ))
 			fi
-			# Whether existing to newly created, activate swap
-			swapon  ${PARTITION} >/dev/null 2>>/tmp/.errlog
-			check_for_error
-			# Since a partition was used, remove that partition from the list
-			PARTITIONS=$(echo $PARTITIONS | sed "s~${PARTITION} [0-9]*[G-M]~~" | sed "s~${PARTITION} [0-9]*\.[0-9]*[G-M]~~" | sed s~${PARTITION}$' -'~~)
-			NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS - 1 ))
 		fi
-	fi
 
-}
+	}
+
 	####								####
 	#### MOUNTING FUNCTION BEGINS HERE  ####
 	####								####
@@ -1492,6 +1495,7 @@ install_root(){
   
   # Display Manager
   arch_chroot "systemctl enable lxdm" 2>>/tmp/.errlog
+  # Copy our predefined lxdm.conf
   cp -f /inst/lxdm.conf ${MOUNTPOINT}/etc/lxdm/lxdm.conf 2>>/tmp/.errlog
   [[ -d ${MOUNTPOINT}/inst ]] && rm -R ${MOUNTPOINT}/inst &> /dev/null 2>>/tmp/.errlog
   check_for_error
@@ -1598,8 +1602,10 @@ uefi_bootloader() {
 		BOOTLOADER="grub"
 
 	elif [[ $(cat ${ANSWER}) == "systemd-boot" ]];then
-
-		arch_chroot "bootctl --path=${UEFI_MOUNT} install" 2>/tmp/.errlog
+        echo ${UEFI_MOUNT}
+        
+		#arch_chroot "bootctl --path=${UEFI_MOUNT} install" 2>/tmp/.errlog
+		bootctl --path=${MOUNTPOINT}${UEFI_MOUNT} install 2>/tmp/.errlog
 		check_for_error
 				
 		# Deal with LVM Root
